### ISSUE TITLE
about the code: x_adv = x_adv - eps*x_adv.grad

### ISSUE THREAD

**Issue by luckwyy** [1Konny/FGSM#4]
Isn't it supposed to be # x_adv = x_adv + eps*x_adv.grad?

**Comment by YeRen123455** [comment]
Hi @luckywyy !
   I have the same question with you. Do you solve it?

**Comment by luckwyy** [comment]
No, I acquiesce the default code is right.

**Comment by YeRen123455** [comment]
But other repos use gradient ascent (i.e., x_adv = x_adv + eps*x_adv.grad) to attack initial image. So, which one is right  - -!

**Comment by jahidhasanlinix** [comment]
Hi @luckywyy @YeRen123455  What did you put into **[NAME]** to run the code? Thank you:)
`python main.py --mode train --env_name [NAME]`
